### ISSUE TITLE
.vscode in .gitignore?

### ISSUE THREAD

**Issue by joshinils** [osmberlin/osm-traffic-sign-tool#17]
eigntlich sind das ja lokale einstellungen die ncihts mit dem projekt zu tun haben, oder?

**Comment by tordans** [comment]
Die extensions.json enthält Empfehlungen die für alle Devs die VS Code verwenden und das Projekt bearbeiten wichtig sind.
VS Code hat dann einen Dialog, der die Extension empfiehlt.

Ich schließe erstmal; wenn du Konflikte siehst, gerne wieder öffnen.
