### ISSUE TITLE
Fahrradstraße

### ISSUE THREAD

**Issue by Langlaeufer** [osmberlin/osm-traffic-sign-tool#44]
Bitte bicycle=desingated hinzufügen, da sonst auch Radfahrer durch vehicle=no/destination/... ausgesperrt werden.

Die expliziten Tags überschreiben die (vielleicht) impliziten. D.h. ein implizites bicycle=designated wird durch das immer zu setzende vehicle=*  überschrieben. Die Radfahrer müssen nun wieder explizt freigegeben werden.

https://trafficsigns.osm-verkehrswende.org/?signs=DE%3A244.1%7CDE%3A1020-30

**Comment by tordans** [comment]
Thanks @Langlaeufer I just release a rewrite of the app and this case is now solved:

https://trafficsigns.osm-verkehrswende.org/DE?signs=DE:244.1,1020-30

<img width="666" alt="image" src="https://github.com/user-attachments/assets/ec26d82c-c31a-40dd-a433-f99770fffa07">
