### ISSUE TITLE
Kombinationen von Rad/Fußweg mit ... frei

### ISSUE THREAD

**Issue by Langlaeufer** [osmberlin/osm-traffic-sign-tool#53]
Bei diesen Kombinitionen von Sonderweg (237-241) mit Freigabe durch Zusatzzeichen (Anlieger, Land/Forstwirstschaftlicher Verkehr frei) fehlt die access-Freigabe in den Taggingvorschlägen

https://trafficsigns.osm-verkehrswende.org/?signs=DE:240,DE:1026-36
hier z.b fehlt access=agricultural

**Comment by Langlaeufer** [comment]
Gilt auch für Fußgängerzone.

**Comment by tordans** [comment]
@Langlaeufer Ich mache es jetzt so, dass wenn für Verkehrszeichen-Gruppe kein Access-Tag existiert, der modifiziert oder gesetzt wurde, dann schreibe ich einen `access=*` Wert.

Teste gerne mal, ob das so Sinn macht für verschiedene (realistische) Kombinationen.

https://trafficsigns.osm-verkehrswende.org/DE?signs=DE:240,1026-36
> <img width="370" alt="image" src="https://github.com/user-attachments/assets/c861871d-6a03-4132-9859-4145cb1d95b8">

https://trafficsigns.osm-verkehrswende.org/?signs=DE:242.1,DE:1020-30

**Comment by Langlaeufer** [comment]
sieht gut aus
