### ISSUE TITLE
Eingabefelder für eigene Werte defekt

### ISSUE THREAD

**Issue by Tillbtn** [osmberlin/osm-traffic-sign-tool#56]
Bei Eingabe einer Geschwindigkeit / Uhrzeit wird man nach jedem Tastendruck aus dem Eingabefeld geworfen und muss erneut reinklicken, um weiterzutippen

**Comment by tordans** [comment]
Ich habe den Fehler behoben oder sagen wir umgangen. 
Zum testen: https://trafficsigns.osm-verkehrswende.org/DE?signs=DE:274[123],1042-35[Su,PH+6-22]

Man kann das Feld jetzt normal verwenden. Die Daten werden aber nur beim verlassen des Formulars oder nach 2 Sekunden Inaktivität übernommen (und dann wir der Fokus auch weiterhin resettet). Nicht ideal, aber erstmal funktionsfähig…
