### ISSUE TITLE
nur ein Zusatzzeichen wird für access ausgewertet

### ISSUE THREAD

**Issue by Tillbtn** [osmberlin/osm-traffic-sign-tool#59]
## Link

https://trafficsigns.osm-verkehrswende.org/DE?signs=DE:250,1020-30,1026-38

## Issue

bei `traffic_sign=*` wird die richtige Kombination vorgeschlagen, für `vehicle=*` nur das untere Zusatzzeichen

**Comment by tordans** [comment]
@Tillbtn 

ich sehe diese Tags – was würdest du anders erwarten?

```
highway=residential // service;track
vehicle=agricultural;forestry
traffic_sign=DE:250,1020-30,1026-38
```

**Comment by Tillbtn** [comment]
ich würde `vehicle=destination;agricultural;forestry` erwarten.
Dreht man die Reihenfolge der Zusatzzeichen um, erhält man nur `vehicle=destination`

**Comment by tordans** [comment]
Danke @Tillbtn 
https://trafficsigns.osm-verkehrswende.org/DE?signs=DE:250,1020-30,1026-38

Ich habe das jetzt so gebaut…
- alle modifier sign sind additiv in der Reihenfolge, in der sie angegeben sind
- außer sie ein "no" vorfinden, dann überschreiben sie dieses

Teste gerne noch ein paar cases, ob das jetzt besser wie erwartet funktioniert.
